In [1]:
import pandas as pd
import numpy as np 

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC 

In [2]:
# create classifier
lr = LogisticRegression()
rfc = RandomForestClassifier(n_estimators=100)
svc = SVC(kernel='linear', C=1E10)

In [3]:
pose = pd.read_csv("dataset/mydataset.csv")

In [4]:
pose.head(5)

nose_x  nose_y  neck_x  neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
0    0.26    0.41    0.26    0.48         0.23         0.48      0.21   
1    0.34    0.46    0.34    0.52         0.31         0.52      0.29   
2    0.34    0.46    0.34    0.52         0.31         0.52      0.31   
3    0.45    0.39    0.45    0.46         0.42         0.48      0.40   
4    0.56    0.39    0.55    0.46         0.52         0.46      0.51   

   Relbow_y  Rwrist_x  RWrist_y  ...  LAnkle_y  REye_x  REye_y  LEye_x  \
0      0.41      0.23      0.33  ...      0.96    0.24    0.39    0.27   
1      0.61      0.31      0.70  ...      0.96    0.34    0.44    0.34   
2      0.63      0.34      0.67  ...      0.96    0.33    0.44    0.34   
3      0.57      0.40      0.65  ...      0.89    0.44    0.39    0.45   
4      0.57      0.51      0.65  ...      0.91    0.55    0.37    0.56   

   LEye_y  REar_x  REar_y  LEar_x  LEar_y  class  
0    0.39    0.23    0.41    0.28    0.39      1  
1    0.44    0.33    0.46    0.35    0.46      0  
2    0.44    0.32    0.46    0.35    0.46      0  
3    0.39    0.43    0.39    0.46    0.39      1  
4    0.37    0.54    0.39    0.57    0.39      1  

[5 rows x 37 columns]

In [5]:
pose.tail(5)

nose_x  nose_y  neck_x  neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
795    0.34    0.46    0.34    0.52         0.31         0.52      0.28   
796    0.55    0.39    0.55    0.46         0.51         0.48      0.50   
797    0.55    0.39    0.55    0.46         0.51         0.48      0.51   
798    0.71    0.44    0.71    0.52         0.68         0.52      0.67   
799    0.27    0.41    0.27    0.48         0.23         0.48      0.18   

     Relbow_y  Rwrist_x  RWrist_y  ...  LAnkle_y  REye_x  REye_y  LEye_x  \
795      0.61      0.29      0.67  ...      0.96    0.33    0.44    0.34   
796      0.57      0.51      0.65  ...      0.91    0.55    0.37    0.55   
797      0.57      0.51      0.65  ...      0.91    0.55    0.37    0.56   
798      0.59      0.68      0.65  ...      0.91    0.71    0.44    0.71   
799      0.46      0.15      0.37  ...      0.96    0.26    0.39    0.27   

     LEye_y  REar_x  REar_y  LEar_x  LEar_y  class  
795    0.44    0.33    0.46    0.35    0.46      0  
796    0.37    0.52    0.39    0.56    0.39      1  
797    0.37    0.54    0.39    0.56    0.39      1  
798    0.44    0.70    0.46    0.72    0.44      0  
799    0.39    0.24    0.41    0.28    0.39      1  

[5 rows x 37 columns]

In [6]:
pose.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 37 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   nose_x       800 non-null    float64
 1   nose_y       800 non-null    float64
 2   neck_x       800 non-null    float64
 3   neck_y       800 non-null    float64
 4   Rshoulder_x  800 non-null    float64
 5   Rshoulder_y  800 non-null    float64
 6   Relbow_x     800 non-null    float64
 7   Relbow_y     800 non-null    float64
 8   Rwrist_x     800 non-null    float64
 9   RWrist_y     800 non-null    float64
 10  LShoulder_x  800 non-null    float64
 11  LShoulder_y  800 non-null    float64
 12  LElbow_x     800 non-null    float64
 13  LElbow_y     800 non-null    float64
 14  LWrist_x     800 non-null    float64
 15  LWrist_y     800 non-null    float64
 16  RHip_x       800 non-null    float64
 17  RHip_y       800 non-null    float64
 18  RKnee_x      800 non-null    float64
 19  RKnee_y 

In [7]:
pose.shape


(800, 37)

In [8]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(pose, test_size=0.2)

In [9]:
train.shape

(640, 37)

In [10]:
train.head(5)

nose_x  nose_y  neck_x  neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
704    0.63    0.39    0.63    0.44         0.61         0.46      0.57   
84     0.34    0.46    0.34    0.52         0.31         0.52      0.31   
228    0.50    0.39    0.50    0.46         0.48         0.46      0.44   
690    0.50    0.39    0.50    0.46         0.48         0.46      0.44   
599    0.63    0.39    0.63    0.46         0.61         0.46      0.59   

     Relbow_y  Rwrist_x  RWrist_y  ...  LAnkle_y  REye_x  REye_y  LEye_x  \
704      0.39      0.56      0.31  ...      0.91    0.63    0.37    0.65   
84       0.63      0.34      0.67  ...      0.96    0.33    0.44    0.34   
228      0.41      0.43      0.33  ...      0.89    0.50    0.39    0.50   
690      0.41      0.44      0.35  ...      0.89    0.49    0.39    0.50   
599      0.39      0.59      0.31  ...      0.91    0.63    0.37    0.65   

     LEye_y  REar_x  REar_y  LEar_x  LEar_y  class  
704    0.37    0.62    0.37    0.66    0.37      1  
84     0.44    0.32    0.46    0.35    0.46      0  
228    0.39    0.49    0.39    0.51    0.39      1  
690    0.39    0.49    0.39    0.51    0.39      1  
599    0.37    0.62    0.39    0.66    0.37      1  

[5 rows x 37 columns]

In [11]:
test.shape

(160, 37)

In [12]:
test.head(5)

nose_x  nose_y  neck_x  neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
136    0.50    0.39    0.51    0.48         0.48         0.46      0.43   
21     0.59    0.46    0.59    0.52         0.56         0.52      0.55   
592    0.56    0.46    0.56    0.52         0.54         0.52      0.52   
77     0.55    0.39    0.55    0.46         0.52         0.46      0.49   
525    0.71    0.44    0.71    0.52         0.68         0.52      0.67   

     Relbow_y  Rwrist_x  RWrist_y  ...  LAnkle_y  REye_x  REye_y  LEye_x  \
136      0.48      0.39      0.44  ...      0.89    0.50    0.39    0.51   
21       0.61      0.56      0.67  ...      0.89    0.59    0.44    0.60   
592      0.61      0.54      0.65  ...      0.89    0.56    0.44    0.56   
77       0.39      0.52      0.33  ...      0.91    0.55    0.39    0.56   
525      0.59      0.68      0.65  ...      0.91    0.71    0.44    0.71   

     LEye_y  REar_x  REar_y  LEar_x  LEar_y  class  
136    0.39    0.49    0.39    0.52    0.39      1  
21     0.44    0.57    0.46    0.60    0.46      0  
592    0.44    0.55    0.46    0.57    0.46      0  
77     0.37    0.54    0.39    0.57    0.39      1  
525    0.44    0.70    0.46    0.72    0.44      0  

[5 rows x 37 columns]

In [13]:
train.iloc[:,:36].head(5)

nose_x  nose_y  neck_x  neck_y  Rshoulder_x  Rshoulder_y  Relbow_x  \
704    0.63    0.39    0.63    0.44         0.61         0.46      0.57   
84     0.34    0.46    0.34    0.52         0.31         0.52      0.31   
228    0.50    0.39    0.50    0.46         0.48         0.46      0.44   
690    0.50    0.39    0.50    0.46         0.48         0.46      0.44   
599    0.63    0.39    0.63    0.46         0.61         0.46      0.59   

     Relbow_y  Rwrist_x  RWrist_y  ...  LAnkle_x  LAnkle_y  REye_x  REye_y  \
704      0.39      0.56      0.31  ...      0.66      0.91    0.63    0.37   
84       0.63      0.34      0.67  ...      0.38      0.96    0.33    0.44   
228      0.41      0.43      0.33  ...      0.51      0.89    0.50    0.39   
690      0.41      0.44      0.35  ...      0.51      0.89    0.49    0.39   
599      0.39      0.59      0.31  ...      0.66      0.91    0.63    0.37   

     LEye_x  LEye_y  REar_x  REar_y  LEar_x  LEar_y  
704    0.65    0.37    0.62    0.37    0.66    0.37  
84     0.34    0.44    0.32    0.46    0.35    0.46  
228    0.50    0.39    0.49    0.39    0.51    0.39  
690    0.50    0.39    0.49    0.39    0.51    0.39  
599    0.65    0.37    0.62    0.39    0.66    0.37  

[5 rows x 36 columns]

In [14]:
train_feat = train.iloc[:,:36]
train_targ = train["class"]

In [15]:
train_feat.shape

(640, 36)

In [16]:
train_targ.shape

(640,)

In [17]:
type(train_targ)

pandas.core.series.Series

In [18]:
type(train_feat)

pandas.core.frame.DataFrame

In [20]:
lr.fit(train_feat, train_targ)

LogisticRegression()

In [23]:
lr.score(train_feat, train_targ)    #how good our model is?

1.0

In [22]:
lr.coef_

array([[-0.15768619, -2.07668421, -0.10497342, -1.81002701, -0.08552255,
        -1.64064992, -0.41850141, -3.48077661, -0.93381958, -4.73611586,
         0.00883675, -1.61447718,  0.47736414, -4.04974985,  0.80502771,
        -6.27175129, -0.04385548, -1.11173322, -0.09443446, -0.42247237,
        -0.20647566, -0.42830373,  0.01492262, -1.26128714, -0.03064578,
        -0.51719709, -0.26435465, -0.49026611, -0.11808912, -1.92779626,
        -0.08627494, -1.84999785, -0.06615446, -2.13561832,  0.14558285,
        -1.75900686]])

# seting test data

In [24]:
lr.fit(train_feat, train_targ)

LogisticRegression()

In [25]:
test_feat = test.iloc[:,:36]
test_targ = test["class"]

In [26]:
lr.score(train_feat, train_targ)

1.0

In [27]:
lr.score(test_feat, test_targ)

0.99375

In [28]:
lr.predict(test_feat)

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1], dtype=int64)

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
confusion_matrix(lr.predict(train_feat), train_targ)

array([[320,   0],
       [  0, 320]], dtype=int64)

In [32]:
confusion_matrix(lr.predict(test_feat), test_targ)

array([[79,  0],
       [ 1, 80]], dtype=int64)

# Random Forest Classifier

In [33]:
rfc.fit(train_feat, train_targ)

RandomForestClassifier()

In [34]:
rfc.score(train_feat, train_targ)

1.0

In [35]:
rfc.score(test_feat, test_targ)

1.0

In [36]:
rfc.predict(train_feat)

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [37]:
confusion_matrix(rfc.predict(train_feat), train_targ)

array([[320,   0],
       [  0, 320]], dtype=int64)

# Linear SVC model

In [38]:
svc.fit(train_feat, train_targ)

SVC(C=10000000000.0, kernel='linear')

In [39]:
svc.score(train_feat, train_targ)

1.0

In [41]:
svc.score(test_feat, test_targ)

0.99375