In [1]:
import pandas as pd
import numpy as np 

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC 

In [2]:
# create classifier
lr = LogisticRegression()
rfc = RandomForestClassifier(n_estimators=100)
svc = SVC(kernel='linear', C=1E10)

In [3]:
pose = pd.read_csv("dataset/activity_dataset.csv")

In [4]:
pose.head(5)

Nose X      Nose Y      Neck X      Neck Y  Right Shoulder X  \
0  396.296296  208.695652  377.777778  278.260870        362.962963   
1  311.111111  303.260870  338.888889  283.695652        330.555556   
2  288.972222   98.043478  323.305556  124.782609        309.000000   
3  412.953704  487.500000  449.037037  536.956522        461.064815   
4  131.111111   44.130435  124.555556   63.043478        116.907407   

   Right Shoulder Y  Right Elbow X  Right Elbow Y  Right Wrist X  \
0        282.608696     362.962963     282.608696     362.962963   
1        288.586956     330.555556     288.586956     330.555556   
2        129.239130     300.416667     158.206522     303.277778   
3        522.826087     461.064815     522.826087     461.064815   
4         65.565217      98.333333      73.130435      88.500000   

   Right Wrist Y  ...  Left Ankle Y  Right Eye X  Right Eye Y  Left Eye X  \
0     282.608696  ...    273.913044   385.185185   200.000000  385.185185   
1     288.586956  ...    572.282609   313.888889   572.282609  308.333333   
2     149.293478  ...    222.826087   286.111111    91.358696  294.694444   
3     522.826087  ...   1010.326087   324.750000  1010.326087  324.750000   
4      75.652174  ...     92.043478   127.833333    42.869565  127.833333   

    Left Eye Y  Right Ear X  Right Ear Y  Left Ear X  Left Ear Y  Activity  
0   200.000000   362.962963   217.391304  362.962963  217.391304   dancing  
1   288.586956   308.333333   288.586956  311.111111  264.130435   dancing  
2    91.358696   294.694444    91.358696  317.583333   91.358696   dancing  
3  1010.326087   324.750000  1010.326087  412.953704  501.630435   dancing  
4    42.869565   119.092593    49.173913  119.092593   49.173913   dancing  

[5 rows x 37 columns]

In [5]:
pose.tail(5)

Nose X      Nose Y      Neck X      Neck Y  Right Shoulder X  \
743  251.060185   78.500000  231.291667  146.760870        166.055556   
744  158.888889   48.423913  165.000000  104.918478        117.638889   
745  478.333333  118.711956  466.666667  193.456522        400.555556   
746  142.347222   36.130435  141.064815   60.217391        120.546296   
747  182.120370  109.994565  216.907407  160.532609        167.796296   

     Right Shoulder Y  Right Elbow X  Right Elbow Y  Right Wrist X  \
743        143.347826     138.379630     228.673913     162.101852   
744        107.608696      99.305556     166.793478     100.833333   
745        189.059783     385.000000     281.391304     466.666667   
746         58.711957      93.615741      81.293478      75.662037   
747        163.505435     151.425926     225.934783     206.675926   

     Right Wrist Y  ...  Left Ankle Y  Right Eye X  Right Eye Y  Left Eye X  \
743     303.760870  ...    573.391304   245.129630    64.847826  264.898148   
744     220.597826  ...    435.815217   151.250000    40.353261  168.055556   
745     285.788044  ...    690.288043   466.666667   105.521739  490.000000   
746      63.228261  ...    245.385870   138.500000    31.614130  147.476852   
747     258.635870  ...    484.570652   180.074074   101.076087  192.351852   

     Left Eye Y  Right Ear X  Right Ear Y  Left Ear X  Left Ear Y  Activity  
743   71.673913   225.361111    64.847826  276.759259   85.326087  standing  
744   40.353261   140.555556    48.423913  183.333333   45.733696  standing  
745  109.918478   443.333333   109.918478  505.555556  114.315217  standing  
746   33.119565   133.370370    34.625000  152.606482   37.635870  standing  
747  101.076087   192.351852   101.076087  221.000000  107.021739  standing  

[5 rows x 37 columns]

In [6]:
pose.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 37 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Nose X            748 non-null    float64
 1   Nose Y            748 non-null    float64
 2   Neck X            748 non-null    float64
 3   Neck Y            748 non-null    float64
 4   Right Shoulder X  748 non-null    float64
 5   Right Shoulder Y  748 non-null    float64
 6   Right Elbow X     748 non-null    float64
 7   Right Elbow Y     748 non-null    float64
 8   Right Wrist X     748 non-null    float64
 9   Right Wrist Y     748 non-null    float64
 10  Left Shoulder X   748 non-null    float64
 11  Left Shoulder Y   748 non-null    float64
 12  Left Elbow X      748 non-null    float64
 13  Left Elbow Y      748 non-null    float64
 14  Left Wrist X      748 non-null    float64
 15  Left Wrist Y      748 non-null    float64
 16  Right Hip X       748 non-null    float64
 1

In [7]:
pose.shape


(748, 37)

In [8]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(pose, test_size=0.2)

In [9]:
train.shape

(598, 37)

In [10]:
train.head(5)

Nose X      Nose Y      Neck X      Neck Y  Right Shoulder X  \
445  588.888889  286.141304  588.888889  370.516304        522.222222   
191  193.055556   73.369565  180.555556  102.717391        172.222222   
376  249.500000   83.000000  271.500000  112.500000        233.000000   
225  321.481481  102.500000  315.740741  140.000000        275.555556   
598  162.500000   69.565217  156.481482  125.217391        115.856482   

     Right Shoulder Y  Right Elbow X  Right Elbow Y  Right Wrist X  \
445        370.516304     483.333333     491.576087     555.555556   
191        105.978261     148.611111     102.717391     119.444444   
376        101.000000     174.500000     108.500000      97.500000   
225        140.000000     235.370370     185.000000     246.851852   
598        119.652174     111.342593     183.652174     173.032407   

     Right Wrist Y  ...  Left Ankle Y  Right Eye X  Right Eye Y  Left Eye X  \
445     443.885870  ...    590.625000   577.777778   275.135870  605.555556   
191      97.826087  ...    143.478261   188.888889    71.739130  188.888889   
376      97.000000  ...    244.000000   239.000000    75.500000  257.500000   
225     202.500000  ...    450.000000   312.870370    95.000000  330.092593   
598     180.869565  ...    453.565217   154.976852    61.217391  170.023148   

     Left Eye Y  Right Ear X  Right Ear Y  Left Ear X  Left Ear Y  Activity  
445   275.13587   550.000000   286.141304  622.222222  282.472826   sitting  
191    71.73913   179.166667    81.521739  179.166667   81.521739   dancing  
376    70.50000   239.000000    75.500000  281.500000   69.500000   sitting  
225    95.00000   298.518519    97.500000  338.703704   97.500000   running  
598    64.00000   141.435185    66.782609  180.555556   69.565217  standing  

[5 rows x 37 columns]

In [11]:
test.shape

(150, 37)

In [12]:
test.head(5)

Nose X      Nose Y      Neck X      Neck Y  Right Shoulder X  \
8    396.296296  208.695652  377.777778  278.260870        362.962963   
499  204.384259   90.489130  202.824074  141.847826        160.699074   
171   92.250000   95.652174   84.375000  139.130435         68.625000   
484  344.907407   59.543478  326.388889   97.434783        293.981481   
233  440.740741   89.461957  437.037037  129.864130        407.407407   

     Right Shoulder Y  Right Elbow X  Right Elbow Y  Right Wrist X  \
8          282.608696     362.962963     282.608696     362.962963   
499        146.739130     127.935185     220.108696     123.254630   
171        134.782609      68.625000     134.782609      68.625000   
484        101.043478     291.666667     147.956522     321.759259   
233        129.864130     392.592593     181.809783     392.592593   

     Right Wrist Y  ...  Left Ankle Y  Right Eye X  Right Eye Y  Left Eye X  \
8       282.608696  ...    273.913044   385.185185   200.000000  385.185185   
499     242.119565  ...    371.739130   196.583333    78.260870  213.745370   
171     134.782609  ...    134.782609    87.750000    86.956522   97.875000   
484     175.021739  ...    265.239130   335.648148    52.326087  342.592593   
233     181.809783  ...    421.336957   433.333333    83.690217  448.148148   

     Left Eye Y  Right Ear X  Right Ear Y  Left Ear X  Left Ear Y  Activity  
8    200.000000   362.962963   217.391304  362.962963  217.391304   dancing  
499   80.706522   184.101852    83.152174  227.787037   90.489130   sitting  
171   89.130435    77.625000    86.956522  103.500000   97.826087   dancing  
484   52.326087   312.500000    61.347826  312.500000   61.347826   sitting  
233   83.690217   422.222222    89.461957  459.259259   89.461957   running  

[5 rows x 37 columns]

In [13]:
train.iloc[:,:36].head(5)

Nose X      Nose Y      Neck X      Neck Y  Right Shoulder X  \
445  588.888889  286.141304  588.888889  370.516304        522.222222   
191  193.055556   73.369565  180.555556  102.717391        172.222222   
376  249.500000   83.000000  271.500000  112.500000        233.000000   
225  321.481481  102.500000  315.740741  140.000000        275.555556   
598  162.500000   69.565217  156.481482  125.217391        115.856482   

     Right Shoulder Y  Right Elbow X  Right Elbow Y  Right Wrist X  \
445        370.516304     483.333333     491.576087     555.555556   
191        105.978261     148.611111     102.717391     119.444444   
376        101.000000     174.500000     108.500000      97.500000   
225        140.000000     235.370370     185.000000     246.851852   
598        119.652174     111.342593     183.652174     173.032407   

     Right Wrist Y  ...  Left Ankle X  Left Ankle Y  Right Eye X  Right Eye Y  \
445     443.885870  ...    722.222222    590.625000   577.777778   275.135870   
191      97.826087  ...    191.666667    143.478261   188.888889    71.739130   
376      97.000000  ...    190.000000    244.000000   239.000000    75.500000   
225     202.500000  ...    278.425926    450.000000   312.870370    95.000000   
598     180.869565  ...    207.638889    453.565217   154.976852    61.217391   

     Left Eye X  Left Eye Y  Right Ear X  Right Ear Y  Left Ear X  Left Ear Y  
445  605.555556   275.13587   550.000000   286.141304  622.222222  282.472826  
191  188.888889    71.73913   179.166667    81.521739  179.166667   81.521739  
376  257.500000    70.50000   239.000000    75.500000  281.500000   69.500000  
225  330.092593    95.00000   298.518519    97.500000  338.703704   97.500000  
598  170.023148    64.00000   141.435185    66.782609  180.555556   69.565217  

[5 rows x 36 columns]

In [14]:
train_feat = train.iloc[:,:36]
train_targ = train["Activity"]

In [15]:
train_feat.shape

(598, 36)

In [16]:
train_targ.shape

(598,)

In [17]:
type(train_targ)

pandas.core.series.Series

In [18]:
type(train_feat)

pandas.core.frame.DataFrame

In [19]:
lr.fit(train_feat, train_targ)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
lr.score(train_feat, train_targ)    #how good our model is?

0.8478260869565217

In [21]:
lr.coef_

array([[ 0.0066099 ,  0.01358327,  0.00444194,  0.01016566,  0.01438849,
         0.0113556 ,  0.03100213, -0.012745  , -0.02655263, -0.00650041,
        -0.01924362, -0.00681159, -0.03232643, -0.02372392,  0.02186148,
         0.00323138,  0.01198276, -0.01156864, -0.00225214,  0.02208777,
         0.03293007, -0.00297617, -0.02942725, -0.00101762, -0.0159974 ,
         0.01627098,  0.00539511, -0.00123998, -0.0139004 ,  0.01682518,
         0.00425474,  0.0116925 ,  0.01391103, -0.0008596 , -0.00472792,
        -0.01845129],
       [-0.00620302, -0.01370631, -0.00905171, -0.01211512,  0.01986138,
        -0.0128125 ,  0.00575154,  0.00828999,  0.00819886,  0.00828434,
        -0.02227193, -0.00787221,  0.0045071 , -0.00197024, -0.01162541,
        -0.00194179,  0.0145224 , -0.00997877,  0.04642474,  0.0408344 ,
         0.00415585, -0.00934513, -0.01369277, -0.01991261, -0.03877389,
         0.01458888, -0.01843126,  0.00741764,  0.02941783,  0.01334902,
        -0.01221185, -0.00828

# seting test data

In [22]:
lr.fit(train_feat, train_targ)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
test_feat = test.iloc[:,:36]
test_targ = test["Activity"]

In [24]:
lr.score(train_feat, train_targ)

0.8478260869565217

In [25]:
lr.score(test_feat, test_targ)

0.82

In [26]:
lr.predict(test_feat)

array(['dancing', 'standing', 'dancing', 'sitting', 'running', 'running',
       'running', 'sitting', 'standing', 'standing', 'dancing', 'running',
       'standing', 'dancing', 'dancing', 'running', 'standing', 'sitting',
       'running', 'running', 'sitting', 'running', 'running', 'sitting',
       'running', 'running', 'dancing', 'standing', 'dancing', 'dancing',
       'running', 'standing', 'standing', 'standing', 'dancing',
       'sitting', 'sitting', 'dancing', 'standing', 'running', 'sitting',
       'standing', 'standing', 'standing', 'sitting', 'running',
       'dancing', 'sitting', 'sitting', 'sitting', 'dancing', 'standing',
       'running', 'running', 'sitting', 'dancing', 'sitting', 'dancing',
       'running', 'standing', 'standing', 'running', 'sitting', 'dancing',
       'dancing', 'dancing', 'dancing', 'running', 'running', 'dancing',
       'running', 'running', 'dancing', 'dancing', 'sitting', 'running',
       'running', 'standing', 'dancing', 'running', 'stan

In [27]:
from sklearn.metrics import confusion_matrix

In [28]:
confusion_matrix(lr.predict(train_feat), train_targ)

array([[134,  13,   1,  17],
       [ 23, 118,   1,  16],
       [  3,   0, 130,   3],
       [  4,   5,   5, 125]], dtype=int64)

In [29]:
confusion_matrix(lr.predict(test_feat), test_targ)

array([[30,  3,  0,  5],
       [ 5, 32,  1,  5],
       [ 1,  0, 30,  0],
       [ 0,  3,  4, 31]], dtype=int64)

# Random Forest Classifier

In [30]:
rfc.fit(train_feat, train_targ)

RandomForestClassifier()

In [31]:
rfc.score(train_feat, train_targ)

1.0

In [32]:
rfc.score(test_feat, test_targ)

1.0

In [33]:
rfc.predict(train_feat)

array(['sitting', 'dancing', 'sitting', 'running', 'standing', 'sitting',
       'standing', 'running', 'dancing', 'dancing', 'sitting', 'running',
       'standing', 'standing', 'dancing', 'standing', 'dancing',
       'standing', 'sitting', 'dancing', 'standing', 'dancing',
       'standing', 'sitting', 'sitting', 'dancing', 'dancing', 'sitting',
       'standing', 'sitting', 'dancing', 'standing', 'dancing',
       'standing', 'standing', 'standing', 'dancing', 'dancing',
       'running', 'dancing', 'running', 'sitting', 'standing', 'sitting',
       'running', 'sitting', 'running', 'standing', 'dancing', 'standing',
       'sitting', 'dancing', 'running', 'running', 'sitting', 'sitting',
       'running', 'dancing', 'running', 'standing', 'sitting', 'sitting',
       'standing', 'sitting', 'running', 'sitting', 'dancing', 'dancing',
       'running', 'standing', 'running', 'standing', 'dancing', 'running',
       'sitting', 'standing', 'sitting', 'standing', 'dancing', 'sitting',


In [34]:
confusion_matrix(rfc.predict(train_feat), train_targ)

array([[164,   0,   0,   0],
       [  0, 136,   0,   0],
       [  0,   0, 137,   0],
       [  0,   0,   0, 161]], dtype=int64)

# Linear SVC model

In [35]:
svc.fit(train_feat, train_targ)

SVC(C=10000000000.0, kernel='linear')

In [36]:
svc.score(train_feat, train_targ)

1.0

In [37]:
svc.score(test_feat, test_targ)

0.98

In [39]:
svc.predict(test_feat)

array(['dancing', 'sitting', 'dancing', 'sitting', 'running', 'running',
       'running', 'sitting', 'running', 'standing', 'dancing', 'running',
       'standing', 'dancing', 'standing', 'running', 'standing',
       'sitting', 'running', 'running', 'sitting', 'running', 'dancing',
       'sitting', 'running', 'running', 'standing', 'sitting', 'dancing',
       'standing', 'standing', 'standing', 'sitting', 'standing',
       'dancing', 'sitting', 'sitting', 'dancing', 'standing', 'running',
       'sitting', 'standing', 'standing', 'standing', 'sitting',
       'standing', 'dancing', 'sitting', 'sitting', 'sitting', 'dancing',
       'standing', 'running', 'running', 'dancing', 'running', 'sitting',
       'dancing', 'running', 'running', 'standing', 'standing', 'sitting',
       'dancing', 'standing', 'standing', 'dancing', 'running', 'dancing',
       'dancing', 'running', 'running', 'dancing', 'dancing', 'sitting',
       'running', 'running', 'standing', 'dancing', 'running', 's